# Generated by Django 3.1.5 on 2021-01-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
