# Generated by Django 3.1.5 on 2021-01-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0003_auto_20210112_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='created_date',
            field=models.DateField(),
        ),
    ]
