# Generated by Django 3.1.5 on 2021-01-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0005_auto_20210114_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerylist',
            old_name='completed',
            new_name='purchased',
        ),
        migrations.RenameField(
            model_name='grocerylist',
            old_name='completed_date',
            new_name='purhcased_date',
        ),
    ]
